<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-24</name>
   <tag></tag>
   <elementGuidId>8f0707a8-9969-4b0b-9b23-c0a1895c4e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d29ff599-675b-4d9a-864c-a6e6176d8320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-24</value>
      <webElementGuid>504d3aa1-2011-4f87-aba8-e1eae6fa2526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a182ec8-b2c4-4999-be45-489300c46ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-24&quot;)</value>
      <webElementGuid>8aa20260-4c82-4e12-a54d-c46bdf514ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-24']</value>
      <webElementGuid>c6f9772b-a0de-4200-84f3-30015612a23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>9850430e-b017-4f26-af2f-f075ddbdf464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>0bed1029-09de-485d-a31b-d1d2ceee769e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-24' and @type = 'text']</value>
      <webElementGuid>316403a6-4c31-4791-bf44-a5d4e2669de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
